$(document).ready(function(){
    $("#navpopup").hide();
    $("#popupclose").click(function(){
        $("#navpopup").hide();
    });
    $("#popupburger").click(function(){
        $("#navpopup").show();
    });
});